/*
Deployment script for MyAchitofel

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "MyAchitofel"
:setvar DefaultFilePrefix "MyAchitofel"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[adminprojects]...';


GO
CREATE TABLE [dbo].[adminprojects] (
    [adminprojectID] INT           IDENTITY (1, 1) NOT NULL,
    [projectID]      INT           NOT NULL,
    [firstname]      VARCHAR (50)  NOT NULL,
    [lastname]       VARCHAR (50)  NOT NULL,
    [birthdate]      DATE          NOT NULL,
    [Preferedcake]   VARCHAR (MAX) NOT NULL,
    [city]           VARCHAR (50)  NOT NULL,
    [street]         VARCHAR (50)  NOT NULL,
    [housenum]       VARCHAR (50)  NOT NULL,
    [appartnum]      VARCHAR (50)  NOT NULL,
    [zipcode]        VARCHAR (50)  NOT NULL,
    [country]        VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_adminprojects] PRIMARY KEY CLUSTERED ([adminprojectID] ASC)
);


GO
PRINT N'Creating Table [dbo].[adresess]...';


GO
CREATE TABLE [dbo].[adresess] (
    [employeeID]  INT          NOT NULL,
    [addresstype] INT          NOT NULL,
    [city]        VARCHAR (50) NULL,
    [street]      VARCHAR (50) NULL,
    [housenum]    VARCHAR (50) NULL,
    [appartnum]   VARCHAR (50) NULL,
    [zipcode]     VARCHAR (50) NULL,
    [country]     VARCHAR (50) NULL,
    CONSTRAINT [IX_adresess] UNIQUE NONCLUSTERED ([employeeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[bills]...';


GO
CREATE TABLE [dbo].[bills] (
    [customerID]          INT        NOT NULL,
    [month]               INT        NOT NULL,
    [totalbillNIS]        FLOAT (53) NOT NULL,
    [totalbillUSD]        FLOAT (53) NOT NULL,
    [VAT]                 INT        NOT NULL,
    [statuspaymenttypeID] INT        NOT NULL,
    CONSTRAINT [PK_bills] PRIMARY KEY CLUSTERED ([customerID] ASC, [month] ASC)
);


GO
PRINT N'Creating Table [dbo].[cheating]...';


GO
CREATE TABLE [dbo].[cheating] (
    [cheatingID]    INT  IDENTITY (1, 1) NOT NULL,
    [reportID]      INT  NOT NULL,
    [employeeID]    INT  NOT NULL,
    [teamleadernum] INT  NULL,
    [discussdate]   DATE NULL,
    [conclusions]   INT  NULL,
    CONSTRAINT [PK_cheating] PRIMARY KEY CLUSTERED ([cheatingID] ASC)
);


GO
PRINT N'Creating Table [dbo].[customers]...';


GO
CREATE TABLE [dbo].[customers] (
    [customerID]      INT          IDENTITY (1, 1) NOT NULL,
    [customername]    VARCHAR (50) NOT NULL,
    [forgein_company] INT          NOT NULL,
    [teamID]          INT          NOT NULL,
    CONSTRAINT [PK_customers] PRIMARY KEY CLUSTERED ([customerID] ASC)
);


GO
PRINT N'Creating Table [dbo].[daylyreport]...';


GO
CREATE TABLE [dbo].[daylyreport] (
    [reportID]       INT        NOT NULL,
    [employeeID]     INT        NOT NULL,
    [projectID]      INT        NOT NULL,
    [officeID]       INT        NOT NULL,
    [currentdate]    DATE       NOT NULL,
    [starttime]      TIME (7)   NOT NULL,
    [endtime]        TIME (7)   NOT NULL,
    [totalcommute]   FLOAT (53) NOT NULL,
    [totalworkhours] FLOAT (53) NOT NULL,
    CONSTRAINT [PK_daylyreport] PRIMARY KEY CLUSTERED ([reportID] ASC)
);


GO
PRINT N'Creating Table [dbo].[employees]...';


GO
CREATE TABLE [dbo].[employees] (
    [employeeID]      INT          IDENTITY (1, 1) NOT NULL,
    [IDnumber]        VARCHAR (10) NOT NULL,
    [firstname]       VARCHAR (30) NOT NULL,
    [lastname]        VARCHAR (30) NOT NULL,
    [gender]          INT          NOT NULL,
    [statusID]        INT          NULL,
    [Hiredate]        DATE         NOT NULL,
    [Terminationdate] DATE         NULL,
    [title]           VARCHAR (50) NULL,
    [teamID]          INT          NOT NULL,
    [Hearingdec_1]    VARCHAR (50) NULL,
    [Hearingdec_2]    VARCHAR (50) NULL,
    CONSTRAINT [PK_employees] PRIMARY KEY CLUSTERED ([employeeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[employees_socialbenifits]...';


GO
CREATE TABLE [dbo].[employees_socialbenifits] (
    [employeeID]        INT        NOT NULL,
    [benifitID]         INT        NOT NULL,
    [totalbenefitvalue] FLOAT (53) NOT NULL,
    CONSTRAINT [PK_employees_socialbenifits] PRIMARY KEY CLUSTERED ([employeeID] ASC, [benifitID] ASC)
);


GO
PRINT N'Creating Table [dbo].[employeeskids]...';


GO
CREATE TABLE [dbo].[employeeskids] (
    [employeeID] INT          NOT NULL,
    [kidIDnum]   VARCHAR (10) NOT NULL,
    [birthdate]  DATE         NOT NULL,
    [city]       INT          NULL,
    [street]     VARCHAR (50) NULL,
    [housenum]   VARCHAR (50) NULL,
    [appartnum]  VARCHAR (50) NULL,
    [zipcode]    VARCHAR (50) NULL,
    [country]    VARCHAR (50) NULL,
    CONSTRAINT [PK_employeeskids] PRIMARY KEY CLUSTERED ([kidIDnum] ASC)
);


GO
PRINT N'Creating Table [dbo].[employeespartners]...';


GO
CREATE TABLE [dbo].[employeespartners] (
    [employeeID]   INT          NOT NULL,
    [partnerIDnum] VARCHAR (50) NOT NULL,
    [firstname]    VARCHAR (50) NOT NULL,
    [lastname]     VARCHAR (50) NOT NULL,
    [city]         VARCHAR (50) NULL,
    [street]       VARCHAR (50) NULL,
    [housenum]     VARCHAR (50) NULL,
    [appartnum]    VARCHAR (50) NULL,
    [zipcode]      VARCHAR (50) NULL,
    [country]      VARCHAR (50) NULL,
    CONSTRAINT [PK_employeespartners] PRIMARY KEY CLUSTERED ([partnerIDnum] ASC)
);


GO
PRINT N'Creating Table [dbo].[Exchangerate]...';


GO
CREATE TABLE [dbo].[Exchangerate] (
    [date] DATE  NOT NULL,
    [rate] MONEY NOT NULL,
    CONSTRAINT [PK_Exchangerate] PRIMARY KEY CLUSTERED ([date] ASC, [rate] ASC)
);


GO
PRINT N'Creating Table [dbo].[gendertype]...';


GO
CREATE TABLE [dbo].[gendertype] (
    [genderID]    INT          NOT NULL,
    [description] VARCHAR (50) NULL,
    CONSTRAINT [PK_gendertype] PRIMARY KEY CLUSTERED ([genderID] ASC)
);


GO
PRINT N'Creating Table [dbo].[HR_hearing]...';


GO
CREATE TABLE [dbo].[HR_hearing] (
    [hearingID]    INT          IDENTITY (1, 1) NOT NULL,
    [cheatingID]   INT          NOT NULL,
    [hearingdate]  DATE         NOT NULL,
    [decisiontype] VARCHAR (50) NULL,
    CONSTRAINT [PK_hearing] PRIMARY KEY CLUSTERED ([hearingID] ASC)
);


GO
PRINT N'Creating Table [dbo].[managerprojectpartner]...';


GO
CREATE TABLE [dbo].[managerprojectpartner] (
    [managerprojectID] INT           NOT NULL,
    [partnerID]        INT           IDENTITY (1, 1) NOT NULL,
    [firstname]        VARCHAR (50)  NOT NULL,
    [lastname]         VARCHAR (50)  NOT NULL,
    [preferedcake]     VARCHAR (MAX) NOT NULL,
    [birthdate]        DATE          NOT NULL,
    [city]             VARCHAR (50)  NOT NULL,
    [street]           VARCHAR (50)  NOT NULL,
    [housenum]         VARCHAR (50)  NOT NULL,
    [appratnum]        VARCHAR (50)  NOT NULL,
    [zipcode]          VARCHAR (50)  NOT NULL,
    [country]          VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_managerprojectpartner] PRIMARY KEY CLUSTERED ([partnerID] ASC)
);


GO
PRINT N'Creating Table [dbo].[managerprojectskids]...';


GO
CREATE TABLE [dbo].[managerprojectskids] (
    [managerprojectID] INT           NOT NULL,
    [kidID]            INT           IDENTITY (1, 1) NOT NULL,
    [birthdate]        DATE          NOT NULL,
    [preferedcake]     VARCHAR (MAX) NOT NULL,
    [city]             VARCHAR (50)  NOT NULL,
    [street]           VARCHAR (50)  NOT NULL,
    [housenum]         VARCHAR (50)  NOT NULL,
    [zipcode]          VARCHAR (50)  NOT NULL,
    [country]          VARCHAR (50)  NOT NULL,
    [firstname]        VARCHAR (50)  NOT NULL,
    [lastname]         VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_managerprojectskids] PRIMARY KEY CLUSTERED ([kidID] ASC)
);


GO
PRINT N'Creating Table [dbo].[managersprojects]...';


GO
CREATE TABLE [dbo].[managersprojects] (
    [managerprojectID] INT           IDENTITY (1, 1) NOT NULL,
    [adminprojectID]   INT           NOT NULL,
    [firstname]        VARCHAR (50)  NOT NULL,
    [lastname]         VARCHAR (50)  NOT NULL,
    [birthdate]        DATE          NOT NULL,
    [preferedcake]     VARCHAR (MAX) NOT NULL,
    [city]             VARCHAR (50)  NOT NULL,
    [street]           VARCHAR (50)  NOT NULL,
    [housenum]         VARCHAR (50)  NOT NULL,
    [appartnum]        VARCHAR (50)  NOT NULL,
    [zipcode]          VARCHAR (50)  NOT NULL,
    [country]          VARCHAR (50)  NOT NULL,
    CONSTRAINT [PK_managersprojects] PRIMARY KEY CLUSTERED ([managerprojectID] ASC)
);


GO
PRINT N'Creating Table [dbo].[maritalstatus]...';


GO
CREATE TABLE [dbo].[maritalstatus] (
    [statusID]   INT          NOT NULL,
    [desciption] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_maritalstatus] PRIMARY KEY CLUSTERED ([statusID] ASC)
);


GO
PRINT N'Creating Table [dbo].[offices]...';


GO
CREATE TABLE [dbo].[offices] (
    [officeID]   INT          IDENTITY (1, 1) NOT NULL,
    [customerID] INT          NOT NULL,
    [officename] VARCHAR (50) NULL,
    [city]       VARCHAR (50) NULL,
    [street]     VARCHAR (50) NULL,
    [housenum]   VARCHAR (50) NULL,
    [appartnum]  VARCHAR (50) NULL,
    [zipcode]    VARCHAR (50) NULL,
    [country]    VARCHAR (50) NULL,
    CONSTRAINT [PK_offices] PRIMARY KEY CLUSTERED ([officeID] ASC)
);


GO
PRINT N'Creating Table [dbo].[Parameters]...';


GO
CREATE TABLE [dbo].[Parameters] (
    [Male_TaxPoint]         FLOAT (53) NOT NULL,
    [Male_KidsTaxPoint]     FLOAT (53) NOT NULL,
    [Female_TaxPoint]       FLOAT (53) NOT NULL,
    [Female_KidsTaxPoint]   FLOAT (53) NOT NULL,
    [MangerAdditional]      FLOAT (53) NOT NULL,
    [VAT]                   FLOAT (53) NOT NULL,
    [SabbathWork]           FLOAT (53) NOT NULL,
    [HollidayWork]          FLOAT (53) NOT NULL,
    [HollidayandSabbatWork] FLOAT (53) NOT NULL,
    [BlackListFee]          FLOAT (53) NOT NULL,
    [ExtraHours]            FLOAT (53) NOT NULL
);


GO
PRINT N'Creating Table [dbo].[projects]...';


GO
CREATE TABLE [dbo].[projects] (
    [projectID]     INT        IDENTITY (1, 1) NOT NULL,
    [projectname]   NCHAR (10) NULL,
    [adminproject]  NCHAR (10) NULL,
    [statuspayment] INT        NOT NULL,
    [custonerID]    INT        NOT NULL,
    CONSTRAINT [PK_projects] PRIMARY KEY CLUSTERED ([projectID] ASC)
);


GO
PRINT N'Creating Table [dbo].[salaries]...';


GO
CREATE TABLE [dbo].[salaries] (
    [employeeID]      INT        NOT NULL,
    [month]           DATE       NOT NULL,
    [year]            DATE       NOT NULL,
    [totalhours]      FLOAT (53) NOT NULL,
    [totalbasesalary] FLOAT (53) NOT NULL,
    [totalbenefits]   FLOAT (53) NULL,
    CONSTRAINT [PK_salaries] PRIMARY KEY CLUSTERED ([employeeID] ASC, [month] ASC, [year] ASC)
);


GO
PRINT N'Creating Table [dbo].[socialbenifits]...';


GO
CREATE TABLE [dbo].[socialbenifits] (
    [benifitID]     INT          IDENTITY (1, 1) NOT NULL,
    [description]   VARCHAR (50) NULL,
    [salarypercent] FLOAT (53)   NOT NULL,
    CONSTRAINT [PK_socialbenifits] PRIMARY KEY CLUSTERED ([benifitID] ASC)
);


GO
PRINT N'Creating Table [dbo].[teams]...';


GO
CREATE TABLE [dbo].[teams] (
    [teamID]        INT IDENTITY (1, 1) NOT NULL,
    [teamleadernum] INT NOT NULL,
    CONSTRAINT [PK_teams] PRIMARY KEY CLUSTERED ([teamID] ASC)
);


GO
PRINT N'Creating Table [dbo].[wage_project_per_employee]...';


GO
CREATE TABLE [dbo].[wage_project_per_employee] (
    [employeeID] INT   NOT NULL,
    [projectID]  INT   NOT NULL,
    [wage]       MONEY NOT NULL,
    [currency]   INT   NOT NULL,
    CONSTRAINT [PK_wage_project_per_employee] PRIMARY KEY CLUSTERED ([employeeID] ASC, [projectID] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_adminprojects_typeID]...';


GO
ALTER TABLE [dbo].[adminprojects]
    ADD CONSTRAINT [DF_adminprojects_typeID] DEFAULT ((1)) FOR [Preferedcake];


GO
PRINT N'Creating Default Constraint [dbo].[DF_managerprojectpartner_typeID]...';


GO
ALTER TABLE [dbo].[managerprojectpartner]
    ADD CONSTRAINT [DF_managerprojectpartner_typeID] DEFAULT ((1)) FOR [preferedcake];


GO
PRINT N'Creating Default Constraint [dbo].[DF_managerprojectskids_typeID]...';


GO
ALTER TABLE [dbo].[managerprojectskids]
    ADD CONSTRAINT [DF_managerprojectskids_typeID] DEFAULT ((1)) FOR [preferedcake];


GO
PRINT N'Creating Default Constraint [dbo].[DF_managersprojects_typeID]...';


GO
ALTER TABLE [dbo].[managersprojects]
    ADD CONSTRAINT [DF_managersprojects_typeID] DEFAULT ((1)) FOR [preferedcake];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Table_1_maletaxpoint]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Table_1_maletaxpoint] DEFAULT ((2)) FOR [Male_TaxPoint];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Parameters_male_kidstaxpoint]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Parameters_male_kidstaxpoint] DEFAULT ((0.5)) FOR [Male_KidsTaxPoint];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Parameters_female_taxpoint]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Parameters_female_taxpoint] DEFAULT ((4.0)) FOR [Female_TaxPoint];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Parameters_female_kidstaxpoint]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Parameters_female_kidstaxpoint] DEFAULT ((1.2)) FOR [Female_KidsTaxPoint];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Parameters_mangeradditional]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Parameters_mangeradditional] DEFAULT ((1.32)) FOR [MangerAdditional];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Parameters_vat]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Parameters_vat] DEFAULT ((1.18)) FOR [VAT];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Table_1_sabbatworking]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Table_1_sabbatworking] DEFAULT ((1.5)) FOR [SabbathWork];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Parameters_hollidaywork]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Parameters_hollidaywork] DEFAULT ((2.2)) FOR [HollidayWork];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Parameters_HollidayandSabbatWork]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Parameters_HollidayandSabbatWork] DEFAULT ((2.5)) FOR [HollidayandSabbatWork];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Parameters_BlackListFee]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Parameters_BlackListFee] DEFAULT ((2)) FOR [BlackListFee];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Parameters_ExtraHours]...';


GO
ALTER TABLE [dbo].[Parameters]
    ADD CONSTRAINT [DF_Parameters_ExtraHours] DEFAULT ((1.3)) FOR [ExtraHours];


GO
PRINT N'Creating Foreign Key [dbo].[FK_adminprojects_projects]...';


GO
ALTER TABLE [dbo].[adminprojects] WITH NOCHECK
    ADD CONSTRAINT [FK_adminprojects_projects] FOREIGN KEY ([projectID]) REFERENCES [dbo].[projects] ([projectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_adresess_employees]...';


GO
ALTER TABLE [dbo].[adresess] WITH NOCHECK
    ADD CONSTRAINT [FK_adresess_employees] FOREIGN KEY ([employeeID]) REFERENCES [dbo].[employees] ([employeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_bills_customers]...';


GO
ALTER TABLE [dbo].[bills] WITH NOCHECK
    ADD CONSTRAINT [FK_bills_customers] FOREIGN KEY ([customerID]) REFERENCES [dbo].[customers] ([customerID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_cheating_daylyreport]...';


GO
ALTER TABLE [dbo].[cheating] WITH NOCHECK
    ADD CONSTRAINT [FK_cheating_daylyreport] FOREIGN KEY ([reportID]) REFERENCES [dbo].[daylyreport] ([reportID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_customers_teams]...';


GO
ALTER TABLE [dbo].[customers] WITH NOCHECK
    ADD CONSTRAINT [FK_customers_teams] FOREIGN KEY ([teamID]) REFERENCES [dbo].[teams] ([teamID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_daylyreport_employees]...';


GO
ALTER TABLE [dbo].[daylyreport] WITH NOCHECK
    ADD CONSTRAINT [FK_daylyreport_employees] FOREIGN KEY ([employeeID]) REFERENCES [dbo].[employees] ([employeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_employees_gendertype]...';


GO
ALTER TABLE [dbo].[employees] WITH NOCHECK
    ADD CONSTRAINT [FK_employees_gendertype] FOREIGN KEY ([gender]) REFERENCES [dbo].[gendertype] ([genderID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_employees_maritalstatus]...';


GO
ALTER TABLE [dbo].[employees] WITH NOCHECK
    ADD CONSTRAINT [FK_employees_maritalstatus] FOREIGN KEY ([statusID]) REFERENCES [dbo].[maritalstatus] ([statusID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_employees_teams]...';


GO
ALTER TABLE [dbo].[employees] WITH NOCHECK
    ADD CONSTRAINT [FK_employees_teams] FOREIGN KEY ([teamID]) REFERENCES [dbo].[teams] ([teamID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_employees_socialbenifits_employees]...';


GO
ALTER TABLE [dbo].[employees_socialbenifits] WITH NOCHECK
    ADD CONSTRAINT [FK_employees_socialbenifits_employees] FOREIGN KEY ([employeeID]) REFERENCES [dbo].[employees] ([employeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_employees_socialbenifits_socialbenifits]...';


GO
ALTER TABLE [dbo].[employees_socialbenifits] WITH NOCHECK
    ADD CONSTRAINT [FK_employees_socialbenifits_socialbenifits] FOREIGN KEY ([benifitID]) REFERENCES [dbo].[socialbenifits] ([benifitID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_employeeskids_employees]...';


GO
ALTER TABLE [dbo].[employeeskids] WITH NOCHECK
    ADD CONSTRAINT [FK_employeeskids_employees] FOREIGN KEY ([employeeID]) REFERENCES [dbo].[employees] ([employeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_employeespartners_employees]...';


GO
ALTER TABLE [dbo].[employeespartners] WITH NOCHECK
    ADD CONSTRAINT [FK_employeespartners_employees] FOREIGN KEY ([employeeID]) REFERENCES [dbo].[employees] ([employeeID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_HR_hearing_cheating]...';


GO
ALTER TABLE [dbo].[HR_hearing] WITH NOCHECK
    ADD CONSTRAINT [FK_HR_hearing_cheating] FOREIGN KEY ([cheatingID]) REFERENCES [dbo].[cheating] ([cheatingID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_managerprojectpartner_managersprojects]...';


GO
ALTER TABLE [dbo].[managerprojectpartner] WITH NOCHECK
    ADD CONSTRAINT [FK_managerprojectpartner_managersprojects] FOREIGN KEY ([managerprojectID]) REFERENCES [dbo].[managersprojects] ([managerprojectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_managerprojectskids_managersprojects]...';


GO
ALTER TABLE [dbo].[managerprojectskids] WITH NOCHECK
    ADD CONSTRAINT [FK_managerprojectskids_managersprojects] FOREIGN KEY ([managerprojectID]) REFERENCES [dbo].[managersprojects] ([managerprojectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_managersprojects_adminprojects]...';


GO
ALTER TABLE [dbo].[managersprojects] WITH NOCHECK
    ADD CONSTRAINT [FK_managersprojects_adminprojects] FOREIGN KEY ([adminprojectID]) REFERENCES [dbo].[adminprojects] ([adminprojectID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_offices_customers]...';


GO
ALTER TABLE [dbo].[offices] WITH NOCHECK
    ADD CONSTRAINT [FK_offices_customers] FOREIGN KEY ([customerID]) REFERENCES [dbo].[customers] ([customerID]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_projects_customers]...';


GO
ALTER TABLE [dbo].[projects] WITH NOCHECK
    ADD CONSTRAINT [FK_projects_customers] FOREIGN KEY ([custonerID]) REFERENCES [dbo].[customers] ([customerID]);


GO
PRINT N'Creating Check Constraint [dbo].[CK_employees]...';


GO
ALTER TABLE [dbo].[employees] WITH NOCHECK
    ADD CONSTRAINT [CK_employees] CHECK ([title]='maneger');


GO
PRINT N'Creating Check Constraint [dbo].[CK_HR_hearing_1]...';


GO
ALTER TABLE [dbo].[HR_hearing] WITH NOCHECK
    ADD CONSTRAINT [CK_HR_hearing_1] CHECK ([decisiontype]='a' OR [decisiontype]='b');


GO
PRINT N'Creating Procedure [dbo].[sp_rand]...';


GO
CREATE procedure sp_rand

@a int , @b int
as
begin
 
  select rand(@b - @a)+ @a

end
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[adminprojects] WITH CHECK CHECK CONSTRAINT [FK_adminprojects_projects];

ALTER TABLE [dbo].[adresess] WITH CHECK CHECK CONSTRAINT [FK_adresess_employees];

ALTER TABLE [dbo].[bills] WITH CHECK CHECK CONSTRAINT [FK_bills_customers];

ALTER TABLE [dbo].[cheating] WITH CHECK CHECK CONSTRAINT [FK_cheating_daylyreport];

ALTER TABLE [dbo].[customers] WITH CHECK CHECK CONSTRAINT [FK_customers_teams];

ALTER TABLE [dbo].[daylyreport] WITH CHECK CHECK CONSTRAINT [FK_daylyreport_employees];

ALTER TABLE [dbo].[employees] WITH CHECK CHECK CONSTRAINT [FK_employees_gendertype];

ALTER TABLE [dbo].[employees] WITH CHECK CHECK CONSTRAINT [FK_employees_maritalstatus];

ALTER TABLE [dbo].[employees] WITH CHECK CHECK CONSTRAINT [FK_employees_teams];

ALTER TABLE [dbo].[employees_socialbenifits] WITH CHECK CHECK CONSTRAINT [FK_employees_socialbenifits_employees];

ALTER TABLE [dbo].[employees_socialbenifits] WITH CHECK CHECK CONSTRAINT [FK_employees_socialbenifits_socialbenifits];

ALTER TABLE [dbo].[employeeskids] WITH CHECK CHECK CONSTRAINT [FK_employeeskids_employees];

ALTER TABLE [dbo].[employeespartners] WITH CHECK CHECK CONSTRAINT [FK_employeespartners_employees];

ALTER TABLE [dbo].[HR_hearing] WITH CHECK CHECK CONSTRAINT [FK_HR_hearing_cheating];

ALTER TABLE [dbo].[managerprojectpartner] WITH CHECK CHECK CONSTRAINT [FK_managerprojectpartner_managersprojects];

ALTER TABLE [dbo].[managerprojectskids] WITH CHECK CHECK CONSTRAINT [FK_managerprojectskids_managersprojects];

ALTER TABLE [dbo].[managersprojects] WITH CHECK CHECK CONSTRAINT [FK_managersprojects_adminprojects];

ALTER TABLE [dbo].[offices] WITH CHECK CHECK CONSTRAINT [FK_offices_customers];

ALTER TABLE [dbo].[projects] WITH CHECK CHECK CONSTRAINT [FK_projects_customers];

ALTER TABLE [dbo].[employees] WITH CHECK CHECK CONSTRAINT [CK_employees];

ALTER TABLE [dbo].[HR_hearing] WITH CHECK CHECK CONSTRAINT [CK_HR_hearing_1];


GO
PRINT N'Update complete.';


GO
